### ISSUE TITLE
Investigate error during creation of a project using our template

### ISSUE THREAD

**Issue by LuisValgoi** [LuisValgoi/ui5-webcomponents-react-seed#70]
**Describe the issue**
When you run `npx create-react-app PROJECT_NAME --template ui5-webcomponents-react-seed`
It will work. It will create a project with our seed as template. But with an error at the console.

**Expected behavior**
To work as its currently working, but, without the error.

**Screenshots**
![Screen Shot 2020-10-05 at 14 20 12](https://user-images.githubusercontent.com/8363610/95111443-e275a300-0715-11eb-8b80-a60ce0bdb2ae.png)

**Additional context**

**Comment by marceloschreiber** [comment]
The error is caused due to the project not having git initialized. It is not initialized because of **husky** in the `template.json`.

After creating a new project from the template, there are 2 manual steps:
- Add husky
- Move dev dependencies to `devDependencies`

We can either document this as part of the process or write a `bat/sh` script that does this and document that it needs to be run after the project is created.

**Comment by LuisValgoi** [comment]
Solved and also will be ready once we migrate to seed.
https://github.com/SAP/ui5-webcomponents-react/pull/790
